services:
  - type: web
    name: real-time-monitoring-inspection-system
    runtime: python
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn dosje_backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
