# Generated by Django 4.2.30 on 2026-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog_current_hash_auditlog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('official', 'Official'), ('inspector', 'Inspector'), ('ngo', 'NGO'), ('nss_volunteer', 'NSS Volunteer')], max_length=20),
        ),
    ]
